<a href="https://colab.research.google.com/github/smonga612/streamlit/blob/main/Wine_Quality_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing the dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection  import train_test_split
from sklearn.metrics import accuracy_score
import seaborn as sns
from sklearn.svm import SVC


Data Collection and Data Processing

In [ ]:
wine_data=pd.read_csv("/content/winequality-white.csv",header=0)

In [ ]:
wine_data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4843            5.6              0.34         0.25             2.5      0.046   
4844            4.8              0.29         0.23             1.1      0.044   
4845            6.6              0.38         0.29             2.4      0.136   
4846            5.1              0.30         0.30             2.3      0.048   
4847            4.4              0.54         0.09             5.1      0.038   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4843                 47.0                 182.0  0.99093  3.21       0.40   
4844                 38.0                 180.0  0.98924  3.28       0.34   
4845                 15.0                  93.0  0.99336  3.18       0.60   
4846                 40.0                 150.0  0.98944  3.29       0.46   
4847                 52.0                  97.0  0.99022  3.41       0.40   

      alcohol  quality  
0         8.8        6  
1         9.5        6  
2        10.1        6  
3         9.9        6  
4         9.9        6  
...       ...      ...  
4843     11.3        5  
4844     11.9        6  
4845      9.5        5  
4846     12.2        6  
4847     12.2        7  

[4848 rows x 12 columns]

In [ ]:
wine_data['volatile acidity'].value_counts()

0.280    263
0.240    251
0.260    240
0.250    230
0.220    226
        ... 
0.850      1
0.930      1
0.545      1
0.910      1
0.405      1
Name: volatile acidity, Length: 124, dtype: int64

In [ ]:
wine_data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
#Y=wine_data['quality'].apply( lambda yvalue: 1 if yvalue > 5 else 0)

In [ ]:
wine_data.loc[wine_data['quality'] <= 5, 'quality'] = 0

In [ ]:
wine_data.loc[wine_data['quality'] > 5, 'quality'] = 1

In [ ]:
wine_data['quality']

0       1
1       1
2       1
3       1
4       1
       ..
4843    0
4844    1
4845    0
4846    1
4847    1
Name: quality, Length: 4848, dtype: int64

In [ ]:
wine_data.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4848.000000       4848.000000  4848.000000     4848.000000   
mean        6.862222          0.277809     0.334398        6.409004   
std         0.842741          0.100723     0.121233        5.079542   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4848.000000          4848.000000           4848.000000  4848.000000   
mean      0.045830            35.321782            138.515780     0.994044   
std       0.021925            16.992805             42.552774     0.002992   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991740   
50%       0.043000            34.000000            134.000000     0.993800   
75%       0.050000            46.000000            167.000000     0.996128   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  4848.000000  4848.000000  4848.000000  4848.000000  
mean      3.188383     0.489736    10.512039     0.664604  
std       0.151244     0.114007     1.230154     0.472177  
min       2.720000     0.220000     8.000000     0.000000  
25%       3.090000     0.410000     9.500000     0.000000  
50%       3.180000     0.470000    10.400000     1.000000  
75%       3.280000     0.550000    11.400000     1.000000  
max       3.820000     1.060000    14.200000     1.000000

In [ ]:
wine_data.shape

(4848, 12)

In [ ]:
wine_data['quality'].value_counts()

1    3222
0    1626
Name: quality, dtype: int64

In [ ]:
wine_data.groupby('quality').mean()

fixed acidity  volatile acidity  citric acid  residual sugar  \
quality                                                                 
0             6.968204          0.309978     0.334563        7.075892   
1             6.808737          0.261575     0.334314        6.072455   

         chlorides  free sulfur dioxide  total sulfur dioxide   density  \
quality                                                                   
0         0.051487            35.325646            148.695264  0.995175   
1         0.042975            35.319832            133.378647  0.993474   

               pH  sulphates    alcohol  
quality                                  
0        3.170234   0.481371   9.849444  
1        3.197542   0.493957  10.846420

separating data and labels

In [ ]:
X=wine_data.drop(columns='quality',axis=1)

In [ ]:
print(X)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4843            5.6              0.34         0.25             2.5      0.046   
4844            4.8              0.29         0.23             1.1      0.044   
4845            6.6              0.38         0.29             2.4      0.136   
4846            5.1              0.30         0.30             2.3      0.048   
4847            4.4              0.54         0.09             5.1      0.038   

      free sulfur dioxide  

In [ ]:
print(X)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4843            5.6              0.34         0.25             2.5      0.046   
4844            4.8              0.29         0.23             1.1      0.044   
4845            6.6              0.38         0.29             2.4      0.136   
4846            5.1              0.30         0.30             2.3      0.048   
4847            4.4              0.54         0.09             5.1      0.038   

      free sulfur dioxide  

In [ ]:
Y=wine_data['quality']

In [ ]:
print(Y)

0       1
1       1
2       1
3       1
4       1
       ..
4843    0
4844    1
4845    0
4846    1
4847    1
Name: quality, Length: 4848, dtype: int64


Training and Testing Data

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X.values,Y.values,test_size=0.2,stratify=Y,random_state=7)

In [ ]:
print(X_train.shape,Y_train.shape)


(3878, 11) (3878,)


In [ ]:
classifier=SVC(kernel='linear')


In [ ]:
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

In [ ]:
#accuracy on training data

In [ ]:
print(X_train)

[[ 6.    0.24  0.34 ...  3.44  0.44 11.45]
 [ 6.9   0.28  0.28 ...  3.03  0.56 10.4 ]
 [ 5.8   0.28  0.35 ...  3.28  0.5  10.2 ]
 ...
 [ 6.    0.29  0.25 ...  3.08  0.43 13.2 ]
 [ 6.5   0.08  0.33 ...  3.34  0.7  12.  ]
 [ 6.6   0.24  0.27 ...  3.24  0.51  9.2 ]]


In [ ]:
X_train_prediction=classifier.predict(X_train)


In [ ]:
print(X_train_prediction)

[1 1 1 ... 1 1 1]


In [ ]:
print(Y_train)

[1 1 0 ... 1 1 0]


In [ ]:
training_data_accuracy=accuracy_score(X_train_prediction, Y_train)

In [ ]:
print("Accuracy on training data ",training_data_accuracy)

Accuracy on training data  0.7478081485301702


In [ ]:
X_test_prediction=classifier.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction, Y_test)

In [ ]:
print("Accuracy on test data ",test_data_accuracy)

Accuracy on test data  0.7536082474226804


In [ ]:
input_data=(6.2,0.53,0.02,0.9,0.035,6,81,0.99234,3.24,0.35,9.5)
input_data_as_numpy_array=np.asarray(input_data)


In [ ]:
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)

In [ ]:
print(input_data_reshaped)

[[6.2000e+00 5.3000e-01 2.0000e-02 9.0000e-01 3.5000e-02 6.0000e+00
  8.1000e+01 9.9234e-01 3.2400e+00 3.5000e-01 9.5000e+00]]


In [ ]:
prediction=classifier.predict(input_data_reshaped)

In [ ]:
print(prediction)

[0]
